FROM archlinux:latest

RUN pacman -Syu --noconfirm && \
    pacman -S --noconfirm glibc

WORKDIR /app
COPY .env .
COPY frontend/ frontend/
COPY images/ images/
COPY wodin .

EXPOSE 6969

ENTRYPOINT ["./wodin"]
